apiVersion: v1
kind: Service
metadata:
  name: ade-anas-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30539
  selector:
    app: ade-anas-app
---
# Create a pod containing the PHP-FPM application (my-php-app)
# and nginx, each mounting the `shared-files` volume to their
# respective /var/www/html directories.

kind: Pod
apiVersion: v1
metadata:
  name: ade-anas-pod
  labels:
    app: ade-anas-app
    configMap: config-map-v1
spec:
  volumes:
    # Create the shared files volume to be used in both pods
    - name: ade-anas-pv
      persistentVolumeClaim:
        claimName: pkl-ade-anas-pv-claim
    
    # Add the ConfigMap we declared above as a volume for the pod
    - name: nginx-config-volume
      configMap:
        name: nginx-config

  containers:
    # Our PHP-FPM application
    - image: abudawud/php-fpm:7-gmz
      name: app
      volumeMounts:
        - name: ade-anas-pv
          mountPath: /var/www/html
    
    # Our nginx container, which uses the configuration declared above,
    # along with the files shared with the PHP-FPM app.
    - image: nginx:1.7.9
      name: nginx
      volumeMounts:
        - name: ade-anas-pv
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
