apiVersion: v1
kind: Service
metadata:
  name: mysql-pkl
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-pkl
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-pkl
spec:
  selector:
    matchLabels:
      app: mysql-pkl
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-pkl
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-pkl
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: toor
        ports:
        - containerPort: 3306
          name: mysql-pkl
        volumeMounts:
        - name: mysql-pkl-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pkl-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pkl-pv-claim
