apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pkl-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.18.8.1
    path: "/mnt/nfs_share/pkl_mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pkl-pv-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
